
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Sun Mar 24 22:08:46 BRT 2024
//----------------------------------------------------

package ExemploCUP;

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int MAIS = 3;
  public static final int PTVIRG = 2;
  public static final int error = 1;
  public static final int MENOS = 4;
  public static final int EOF = 0;
  public static final int INTEIRO = 5;
}

